- name: "bug"
  color: "#d73a4a"
  description: "Something isn't working"
- name: "documentation"
  color: "#e99695"
  description: "Improvements or additions to documentation"
- name: "duplicate"
  color: "#cfd3d7"
  description: "This issue or pull request already exists"
- name: "enhancement"
  color: "#a22eef"
  description: "New feature or request"
- name: "renovate"
  color: "#272895"
- name: "question"
  color: "#d876e3"
- name: "wontfix"
  color: "#ffffff"
  description: "This will not be worked on"
